services:
  - type: web
    name: mr-platform-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: mr-platform-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mr-platform-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: mr-platform-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mr-platform-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: mr-platform-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: LOG_LEVEL
        value: info

databases:
  - name: mr-platform-db
    databaseName: mr_platform
    plan: free
