services:
  - type: web
    name: mr-platform-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mr-platform-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: LOG_LEVEL
        value: info
    dependsOn:
      - mr-platform-db

databases:
  - name: mr-platform-db
    databaseName: mr_platform
    plan: free
    ipAllowList: [] # only allow internal connections
